#!/usr/bin/env bash

if [ -e Gemfile ]; then
  bundle check || bundle install
fi

if [ -e tmp/pids/server.pid ]; then
  rm tmp/pids/server.pid
fi

if [ -e rackup.pid ]; then
  rm rackup.pid
fi

if [ -n "$DATABASE_HOST" ]; then
  until echo < /dev/tcp/$DATABASE_HOST/5432; do
    sleep 1
  done
fi

